### ISSUE TITLE
variáveis

### ISSUE THREAD

**Issue by pedrualves** [danieladuarteng/studying-js#3]
Qual a diferença entre var, const, let e pq não usar var ?

**Comment by daniduarteng** [comment]
No Javascript, existe 3 tipos de declarações que podemos fazer para armazenar valores são eles: var, let e const.

O tipo **var** é usado quando queremos uma variável global, que pode ser alterada a qualquer momento, sendo seu uso não recomendado, pois pode acabar sendo alterada em momentos inoportunos.

O recomendado quando você precisa de uma variável que é usar o **let**, que pode ser alterada sempre que necessário, porém seu escopo é local ou por bloco.

O tipo **const** é uma constante, ou seja é só criada uma vez, pode ser somente lida e diferente da var e let seu valor não pode ser alterado.

**Comment by pedrualves** [comment]
Adiciona isso na wiki ou outros markdown, acrescente o conceito teórico no repositório. 
É uma ótima maneira de exercitar a passagem de conhecimento, além disso pode ajudar outras pessoas.
