### ISSUE TITLE
Qual a diferença ?

### ISSUE THREAD

**Issue by pedrualves** [danieladuarteng/studying-js#4]
Entre os operadores == e === ??

**Comment by daniduarteng** [comment]
== verifica se os valores são iguais
por exemplo: 2 == '2' o resultado será true, pois é o número dois, em ambos os casos

=== verifica o valor e o tipo de dado
no exemplo anterior: 2 === '2' o resultado será false, pois os tipos de dados são diferentes mesmo que os valores sejam iguais

**Comment by pedrualves** [comment]
Adiciona isso na wiki ou outros markdown, acrescente o conceito teórico no repositório.
É uma ótima maneira de exercitar a passagem de conhecimento, além disso pode ajudar outras pessoas.
